### ISSUE TITLE
Lesson 3, endpoints_tester2.py Checks for the wrong Status Code

### ISSUE THREAD

**Issue by dvanbrug** [udacity/APIs#13]
When testing `endpoints2.py` with the `endpoints_tester2.py` code, it would appear that tests 2, 4, and 5 are checking for status `301`.

I could imagine two fixes:
- Either change the status code to `200` for both tests 2, 4, and 5.  This would then cause the solution code in `endpoints_project2sol.py` to pass all tests.
- Or, change the solution code to return a code of 201 for test 2.  This makes sense as test 2 is the `makeANewPuppy()` test.  This would still require a change to `endpoints_tester2.py`.  I am not sure what the status codes for tests 4 and 5 should be.

This issue would be fixed by #9 or #12.

**Comment by acmujica** [comment]
idk if it's correct but when I did this I returned 301 manually so
    return makeANewPuppy(),301

**Comment by dvanbrug** [comment]
This was fixed by #12.
