### ISSUE TITLE
Lesson_3/06_Adding Features to your Mashup/

### ISSUE THREAD

**Issue by capacitate** [udacity/APIs#23]
Hi, 
Thank you for the kind lecture, but I felt empty.... about this quiz(Lesson_3/06_Mashup), 
since the starter code already have a solution.. 

here is the link from discussion forum 

https://discussions.udacity.com/t/lesson-3-project-06-api-starter-code-views-py-already-contains-solution/187890/2

could you please fix the starter code for this quiz?

**Comment by veronikabenkeser** [comment]
Thank you for bring this to our attention! The starter code has been fixed. Happy Learning!
